const state={blueprint:null,sceneIndex:0,shotIndex:0};const $=id=>document.getElementById(id);
function status(id,msg,error){const e=$(id);e.textContent=msg;e.className="status"+(error?" error":"")}
$("buildBtn").onclick=async()=>{const prompt=$("moviePrompt").value.trim();if(!prompt){status("status","Enter your movie idea first.",true);return}const b=$("buildBtn");b.disabled=true;status("status","Building your cinematic blueprint…");try{const r=await fetch("/api/plan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prompt,length:Number($("length").value),genre:$("genre").value,visualStyle:$("visualStyle").value,ratio:$("ratio").value})});const text=await r.text();let d={};try{d=JSON.parse(text)}catch{}if(!r.ok)throw new Error(d.error||"Movie planning service is temporarily unavailable. Please try again.");state.blueprint=d.blueprint;renderBlueprint(d.blueprint);status("status","Blueprint ready.")}catch(e){status("status",e.message,true)}finally{b.disabled=false}};
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function renderBlueprint(b){$("blueprintSection").classList.remove("hidden");$("movieTitle").textContent=b.title||"Untitled Movie";$("movieLogline").textContent=b.logline||"";$("movieMeta").innerHTML=[b.genre,b.visualBible&&b.visualBible.colorGrade,b.visualBible&&b.visualBible.lighting,(b.scenes||[]).length+" scenes"].filter(Boolean).map(x=>"<span>"+esc(x)+"</span>").join("");$("characters").innerHTML=(b.characters||[]).map(c=>"<div class=\"character\"><h3>"+esc(c.name)+"</h3><p><b>"+esc(c.role)+"</b><br>"+esc(c.appearance)+"<br>"+esc(c.wardrobe)+"</p></div>").join("");$("scenes").innerHTML=(b.scenes||[]).map((s,si)=>"<article class=\"scene\"><div class=\"scene-top\"><div><h3>Scene "+(si+1)+": "+esc(s.heading)+"</h3><div class=\"scene-meta\">"+esc(s.location)+" · "+esc(s.time)+" · "+esc(s.duration)+"</div></div></div><p>"+esc(s.purpose)+" "+esc(s.dialogue)+"</p><div class=\"shots\">"+(s.shots||[]).map((sh,hi)=>"<div class=\"shot\"><div class=\"shot-info\"><strong>Shot "+(hi+1)+" · "+esc(sh.framing)+"</strong><span>"+esc(sh.camera)+" · "+esc(sh.lens)+" · "+esc(sh.movement)+"</span></div><button data-s=\""+si+"\" data-h=\""+hi+"\">Open Shot</button></div>").join("")+"</div></article>").join("");document.querySelectorAll(".shot button").forEach(x=>x.onclick=()=>openShot(+x.dataset.s,+x.dataset.h));$("blueprintSection").scrollIntoView({behavior:"smooth",block:"start"})}
function openShot(si,hi){state.sceneIndex=si;state.shotIndex=hi;const s=state.blueprint.scenes[si],sh=s.shots[hi];$("shotStudio").classList.remove("hidden");$("shotTitle").textContent="Scene "+(si+1)+" · Shot "+(hi+1);$("shotDescription").textContent=s.heading||"";$("shotDetails").innerHTML=[["Camera",sh.camera],["Lens",sh.lens],["Framing",sh.framing],["Angle",sh.angle],["Movement",sh.movement],["Focus",sh.focus],["Lighting",sh.lighting],["Sound",sh.sound],["Continuity",sh.continuity]].filter(x=>x[1]).map(x=>"<div class=\"detail\"><b>"+esc(x[0])+"</b><span>"+esc(x[1])+"</span></div>").join("");$("shotVideo").classList.add("hidden");$("shotVideo").removeAttribute("src");$("videoPlaceholder").classList.remove("hidden");status("shotStatus","");$("shotStudio").scrollIntoView({behavior:"smooth",block:"start"})}
$("generateShotBtn").onclick=generateShot;$("closeStudio").onclick=()=>{$("shotStudio").classList.add("hidden")};$("newMovieBtn").onclick=()=>window.scrollTo({top:0,behavior:"smooth"});
async function generateShot(){if(!state.blueprint)return;const b=$("generateShotBtn");b.disabled=true;status("shotStatus","Sending shot to the video generator…");try{const r=await fetch("/api/generate-shot",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({blueprint:state.blueprint,sceneIndex:state.sceneIndex,shotIndex:state.shotIndex,ratio:$("ratio").value})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Shot generation failed.");if(d.videoUrl){showVideo(d.videoUrl);status("shotStatus","Shot ready.")}else if(d.taskId){await pollTask(d.taskId)}else throw new Error("The video provider did not return a task.")}catch(e){status("shotStatus",e.message,true)}finally{b.disabled=false}}
async function pollTask(id){for(let i=0;i<90;i++){status("shotStatus","Generating cinematic shot… "+Math.min(99,Math.round((i+1)/90*100))+"%");await new Promise(r=>setTimeout(r,5000));const r=await fetch("/api/generate-shot?taskId="+encodeURIComponent(id));const d=await r.json();if(!r.ok)throw new Error(d.error||"Video status check failed.");if(d.status==="SUCCEEDED"&&d.videoUrl){showVideo(d.videoUrl);status("shotStatus","Shot ready.");return}if(d.status==="FAILED"||d.status==="CANCELED")throw new Error("The shot could not be generated. Your project was not changed.")}throw new Error("Generation is taking longer than expected. Check the shot again shortly.")}
function showVideo(url){$("videoPlaceholder").classList.add("hidden");$("shotVideo").src=url;$("shotVideo").classList.remove("hidden");$("shotVideo").load()}
